---
pantalla:
 - alto: 700
 - ancho: 1200

configuracion:
 - vel_personaje: 3
 - margen_scroll: 30

tipos:
 - nombre: agua
   imagen: img/agua.png
   miniImagen: img/tile_blue.png

 - nombre: piedra
   categoria: resource
   imagen: img/piedra.png
   miniImagen: img/tile_blue.png
   ancho_base: 1
   alto_base : 1
   pixel_ref_x: 43
   pixel_ref_y: 9
   
 - nombre: comida
   categoria: resource
   imagen: img/arbusto.png
   miniImagen: img/tile_blue.png
   ancho_base: 1
   alto_base : 1
   pixel_ref_x: 42
   pixel_ref_y: 16
   
 - nombre: oro
   categoria: resource
   imagen: img/oro.png
   miniImagen: img/tile_blue.png
   ancho_base: 1
   alto_base : 1
   pixel_ref_x: 40
   pixel_ref_y: 8

 - nombre: casa
   categoria: building
   imagen: img/casa2x2.png
   miniImagen: img/tile_orange.png
   imagenBoton: img/boton-casa.png
   ancho_base: 4
   alto_base : 4
   pixel_ref_x: 153
   pixel_ref_y: 31
   creables:
   - aldeano
   
 - nombre: archeryRange
   categoria: building
   imagen: img/archeryRange.png
   miniImagen: img/tile_orange.png
   imagenBoton: img/boton-arqueria.png
   ancho_base: 6
   alto_base : 4
   pixel_ref_x: 159
   pixel_ref_y: 77
   creables:
   - soldado

 - nombre: molino
   categoria: building
   imagen: img/whatermill.png
   miniImagen: img/tile_orange.png
   imagenBoton: img/boton-molino.png
   ancho_base: 4
   alto_base : 4
   pixel_ref_x: 80
   pixel_ref_y: 75
   fps: 10
   ancho_frame: 200
   alto_frame: 145

 - nombre: soldado
   categoria: warrior
   imagen: img/soldadoAge.png
   imagenDeshabilitado: img/soldadoAge.png
   miniImagen: img/tile_red.png
   imagenBoton: img/boton-soldado.png
   ancho_base: 1
   alto_base : 1
   pixel_ref_x: 25
   pixel_ref_y: 35
   fps: 35
   delay: 0
   alto_frame: 50
   ancho_frame: 51
   mini_map_pixel_ref_type: 1
   
 - nombre: aldeano
   categoria: worker
   imagen: img/aldeana_caminando.png
   imagenDeshabilitado: img/soldadoAge.png
   miniImagen: img/tile_red.png
   imagenBoton: img/boton-aldeano.png
   ancho_base: 1
   alto_base : 1
   pixel_ref_x: 14
   pixel_ref_y: 32
   fps: 35
   delay: 0
   alto_frame: 40
   ancho_frame: 24
   mini_map_pixel_ref_type: 1
   creables:
   - molino
   - casa
   - archeryRange
   
 - nombre: caballo
   categoria: warrior
   imagen: img/caballo_caminando.png
   imagenDeshabilitado: img/soldadoAge.png
   miniImagen: img/tile_red.png
   ancho_base: 1
   alto_base : 1
   pixel_ref_x: 48
   pixel_ref_y: 75
   fps: 35
   delay: 0
   alto_frame: 94
   ancho_frame: 89
   mini_map_pixel_ref_type: 1

 - nombre: tierra
   imagen: img/tierra.png
   miniImagen: img/tile_yellow.png
 
 - nombre: arbol
   categoria: recurso
   imagen: img/tree1.png
   miniImagen: img/tile_yellow.png
   ancho_base: 1
   alto_base : 1
   pixel_ref_x: 24
   pixel_ref_y: 48
   fps: 5
   delay: 1
   alto_frame: 64
   ancho_frame: 72


escenario:
 - nombre: orleans
   size_x: 40
   size_y: 40
   
   entidades:

   - [x: 1, y: 7, tipo: casa, equipo: RED]
   - [x: 20, y: 10, tipo: archeryRange, equipo: RED]
   - [x: 1, y: 1, tipo: soldado, equipo: RED]
   - [x: 18, y: 9, tipo: aldeano, equipo: RED]
   - [x: 14, y: 9, tipo: caballo, equipo: RED]
   - [x: 1, y: 2, tipo: soldado, equipo: BLUE]
   - [x: 3, y: 3, tipo: soldado, equipo: RED]
   - [x: 5, y: 10, tipo: piedra]
   - [x: 5, y: 12, tipo: oro]
   - [x: 5, y: 14, tipo: comida]
   - [x: 7, y: 2, tipo: arbol]
   - [x: 7, y: 3, tipo: arbol]
   - [x: 7, y: 4, tipo: arbol]
   - [x: 7, y: 5, tipo: arbol]
   - [x: 6, y: 5, tipo: arbol]   
   - [x: 4, y: 5, tipo: arbol]
   - [x: 4, y: 2, tipo: arbol]
   - [x: 4, y: 3, tipo: arbol]
   - [x: 4, y: 4, tipo: arbol]
   - [x: 4, y: 5, tipo: arbol]
   - [x: 4, y: 6, tipo: arbol]
   - [x: 4, y: 7, tipo: arbol]
   - [x: 5, y: 7, tipo: arbol]
   - [x: 6, y: 7, tipo: arbol]
   - [x: 7, y: 7, tipo: arbol]
   - [x: 8, y: 7, tipo: arbol]
   - [x: 9, y: 7, tipo: arbol]
   - [x: 9, y: 6, tipo: arbol]
   - [x: 9, y: 5, tipo: arbol]
   - [x: 9, y: 4, tipo: arbol]
   - [x: 9, y: 3, tipo: arbol]
   - [x: 9, y: 2, tipo: arbol]
   - [x: 9, y: 1, tipo: arbol]
   - [x: 11, y: 7, tipo: arbol]
   - [x: 11, y: 6, tipo: arbol]
   - [x: 11, y: 5, tipo: arbol]
   - [x: 11, y: 4, tipo: arbol]
   - [x: 11, y: 3, tipo: arbol]
   - [x: 11, y: 2, tipo: arbol]
   - [x: 11, y: 1, tipo: arbol]
   - [x: 11, y: 0, tipo: arbol]
   - [x: 5, y: 5, tipo: arbol]
   
   protagonista:
   - tipo: soldado
     x: 10
     y: 3
