---
pantalla:
 - alto: 640
 - ancho: 800

configuracion:
 - vel_personaje: 3
 - margen_scroll: 30

tipos:
 - nombre: arbol
   imagen: path/a/imagen.png

 - nombre: casa
   imagen: img/casa2x2.png
   ancho_base: 2
   alto_base : 2
   pixel_ref_x: 153
   pixel_ref_y: 31
   
 - nombre: archeryRange
   imagen: img/archeryRange.png
   ancho_base: 3
   alto_base : 3
   pixel_ref_x: 159
   pixel_ref_y: 77

 - nombre: castillo
   imagen: path/a/castillo.png
   ancho_base: 2
   alto_base : 2
   pixel_ref_x: 30
   pixel_ref_y: 40

 - nombre: soldado
   imagen: img/vlad.png
   ancho_base: 1
   alto_base : 1
   pixel_ref_x: 25
   pixel_ref_y: 35
   fps: 3
   delay: 0
   alto_frame: 50
   ancho_frame: 50
 
 - nombre: juana_de_arco
   imagen: path/a/juanadearco.png
   fps: 10
   delay: 5

 - nombre: tierra
   imagen: img/tierra.png

 - nombre: agua
   imagen: img/agua.png
 
 - nombre: arbol
   imagen: img/tree1.png
   ancho_base: 1
   alto_base : 1
   pixel_ref_x: -40
   pixel_ref_y: -5
   fps: 3
   delay: 1
   alto_frame: 64
   ancho_frame: 72

 - nombre: molino
   imagen: img/whatermill.png
   ancho_base: 1
   alto_base : 1
   pixel_ref_x: 80
   pixel_ref_y: 75
   fps: 10
   delay: 1
   ancho_frame: 200
   alto_frame: 145

escenario:
 - nombre: orleans
   size_x: 21
   size_y: 21
   
   entidades:
   - [x: 6, y: 4, tipo: archeryRange]
   - [x: 2, y: 5, tipo: casa]
   - [x: 9, y: 15, tipo: tierra]
   - [x: 9, y: 16, tipo: tierra]
   - [x: 9, y: 17, tipo: tierra]
   - [x: 9, y: 18, tipo: tierra]
   - [x: 10, y: 15, tipo: agua]
   - [x: 10, y: 16, tipo: agua]
   - [x: 10, y: 17, tipo: agua]
   - [x: 10, y: 18, tipo: agua]
   - [x: 11, y: 15, tipo: agua]
   - [x: 11, y: 16, tipo: agua]
   - [x: 11, y: 17, tipo: agua]
   - [x: 11, y: 18, tipo: agua]
   - [x: 100, y: 100, tipo: castillo]
   - [x: 2, y: 2, tipo: molino]
   - [x: 4, y: 2, tipo: arbol]
   - [x: 8, y: 2, tipo: molino]
   - [x: 8, y: 3, tipo: arbol]
   - [x: 12, y: 17, tipo: arbol]
   - [x: 20, y: 7, tipo: arbol]
   
   protagonista:
   - tipo: soldado
     x: 12
     y: 12
