---
pantalla:
 - alto: 800
 - ancho: 1200

configuracion:
 - vel_personaje: 3
 - margen_scroll: 30

tipos:
 - nombre: agua
   imagen: img/agua.png
   miniImagen: img/tile_blue.png

 - nombre: piedra
   categoria: recurso
   imagen: img/Mossy_Stone_Brick.png
   miniImagen: img/tile_blue.png
   ancho_base: 1
   alto_base : 1
   pixel_ref_x: 25
   pixel_ref_y: 25
   
 - nombre: comida
   categoria: recurso
   imagen: img/comida.png
   miniImagen: img/tile_blue.png
   ancho_base: 1
   alto_base : 1
   pixel_ref_x: 0
   pixel_ref_y: 0
   
 - nombre: madera
   imagen: img/madera.png
   miniImagen: img/tile_blue.png
   ancho_base: 1
   alto_base : 1
   pixel_ref_x: 25
   pixel_ref_y: 25

 - nombre: casa
   imagen: img/casa2x2.png
   miniImagen: img/tile_orange.png
   ancho_base: 2
   alto_base : 2
   pixel_ref_x: 153
   pixel_ref_y: 31
   
 - nombre: archeryRange
   imagen: img/archeryRange.png
   miniImagen: img/tile_orange.png
   ancho_base: 2
   alto_base : 2
   pixel_ref_x: 159
   pixel_ref_y: 77

 - nombre: molino
   imagen: img/whatermill.png
   miniImagen: img/tile_orange.png
   ancho_base: 1
   alto_base : 1
   pixel_ref_x: 80
   pixel_ref_y: 75
   fps: 10
   ancho_frame: 200
   alto_frame: 145

 - nombre: soldado
   imagen: img/vlad1.png
   imagenDeshabilitado: img/vlad_grey.png
   miniImagen: img/tile_red.png
   ancho_base: 1
   alto_base : 1
   pixel_ref_x: 25
   pixel_ref_y: 35
   fps: 35
   delay: 0
   alto_frame: 50
   ancho_frame: 50
   mini_map_pixel_ref_type: 1

 - nombre: tierra
   imagen: img/tierra.png
   miniImagen: img/tile_yellow.png
 
 - nombre: arbol
   imagen: img/tree1.png
   miniImagen: img/tile_yellow.png
   ancho_base: 1
   alto_base : 1
   pixel_ref_x: 25
   pixel_ref_y: 25
   fps: 5
   delay: 1
   alto_frame: 64
   ancho_frame: 72


escenario:
 - nombre: orleans
   size_x: 20
   size_y: 20
   
   entidades:

   - [x: 1, y: 7, tipo: casa]
   
   
   - [x: 4, y: 2, tipo: comida]
   - [x: 5, y: 2, tipo: comida]
   - [x: 6, y: 2, tipo: comida]
   - [x: 7, y: 2, tipo: arbol]
   - [x: 7, y: 3, tipo: arbol]
   - [x: 7, y: 4, tipo: arbol]
   - [x: 7, y: 5, tipo: arbol]
   - [x: 6, y: 5, tipo: arbol]   
   - [x: 4, y: 5, tipo: arbol]
   - [x: 4, y: 2, tipo: arbol]
   - [x: 4, y: 3, tipo: arbol]
   - [x: 4, y: 4, tipo: arbol]
   - [x: 4, y: 5, tipo: arbol]
   - [x: 4, y: 6, tipo: arbol]
   - [x: 4, y: 7, tipo: arbol]
   - [x: 5, y: 7, tipo: arbol]
   - [x: 6, y: 7, tipo: arbol]
   - [x: 7, y: 7, tipo: arbol]
   - [x: 8, y: 7, tipo: arbol]
   - [x: 9, y: 7, tipo: arbol]
   - [x: 9, y: 6, tipo: arbol]
   - [x: 9, y: 5, tipo: arbol]
   - [x: 9, y: 4, tipo: arbol]
   - [x: 9, y: 3, tipo: arbol]
   - [x: 9, y: 2, tipo: arbol]
   - [x: 9, y: 1, tipo: arbol]
   - [x: 11, y: 7, tipo: arbol]
   - [x: 11, y: 6, tipo: arbol]
   - [x: 11, y: 5, tipo: arbol]
   - [x: 11, y: 4, tipo: arbol]
   - [x: 11, y: 3, tipo: arbol]
   - [x: 11, y: 2, tipo: arbol]
   - [x: 11, y: 1, tipo: arbol]
   - [x: 11, y: 0, tipo: arbol]
   - [x: 5, y: 5, tipo: arbol]
   
   protagonista:
   - tipo: soldado
     x: 10
     y: 3
